//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace data
{
    using System;
    using System.Collections.Generic;
    
    public partial class posts
    {
        public int pid { get; set; }
        public int uid { get; set; }
        public string text { get; set; }
        public string ruid { get; set; }
        public string reason { get; set; }
    
        public virtual sinaaccounts sinaaccounts { get; set; }
    }
}
