//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace data
{
    using System;
    using System.Collections.Generic;
    
    public partial class sinaaccounts
    {
        public sinaaccounts()
        {
            this.posts = new HashSet<posts>();
        }
    
        public int id { get; set; }
        public string uid { get; set; }
        public int isWaste { get; set; }
        public string name { get; set; }
        public int followers_count { get; set; }
        public int friends_count { get; set; }
        public int statuses_count { get; set; }
        public int favourites_count { get; set; }
    
        public virtual ICollection<posts> posts { get; set; }
    }
}
